version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    working_directory: /go/src/github.com/pragmaticivan/tinyestate-api
    steps:
      - checkout
      - run: make dev-dependencies
      - run:
          name: Run unit tests
          command: |
            make test
