version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run: make dev-dependencies
      - run:
          name: Run unit tests
          command: |
            make test
