---
apiVersion: v1
kind: Service
metadata:
  name: tinyestate-api-service
  labels:
    app: tinyestate-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: tinyestate-api-port
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: tinyestate-api-debug-port
  selector:
    app: tinyestate-api
