apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyestate-api-db-storage-claim
  labels:
    app: tinyestate-api-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
